# Generated by Django 3.1.5 on 2021-01-15 08:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='メールアドレス')),
                ('user_photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='プロフィール写真')),
                ('user_name', models.CharField(max_length=50, verbose_name='ユーザーネーム')),
                ('first_name', models.CharField(max_length=50, verbose_name='姓')),
                ('last_name', models.CharField(max_length=50, verbose_name='名')),
                ('bio', models.TextField(max_length=140, verbose_name='説明文')),
                ('date_of_birth', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('following', models.ManyToManyField(related_name='follower', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
